# Generated by Django 4.0.4 on 2022-08-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_created_producto_updated'),
        ('tienda', '0004_auto_20210222_1202'),
    ]

    operations = [
    ]
